server:
  port: 9005
spring:
  application:
    name: gateway
  cloud:
    inetutils:
      default-ip-address: 127.0.0.1
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.inetutils.default-ip-address}:${spring.application.instance-id:${server.port}}
  client:
    service-url:
     defaultZone: http://localhost:8888/eureka
zuul:
  routes:
    gateway:
       path: /*
       serviceId: consumer
    provider:
       path: /gw-provider/**
  prefix: /servi
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file: D:\develop\java\ide_home\log\gateway.log